<a href="https://colab.research.google.com/github/KengoTobita/python_startup/blob/master/Python_startup_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python入門　自然言語処理編

# Python 基本文法入門
今回のハンズオンでは簡単な説明のみを説明しています。<br>
コードを読んで何をしているか、なんとなく分かれば今日はOKです。<br>
文法の詳細についてはドキュメントなどを参考にしてください。<br>
***
#### print関数
カッコ内の文字を出力します。

In [0]:
print("hello weeyble")

hello weeyble


#### 四則演算
簡単な計算が可能。<br>
演算子はエクセルとだいたい一緒。<br>
πなど高等数学はライブラリが必要。<br>

In [0]:
(123+456)*789

456831

#### 変数の使用
変数を使用することで、コードがわかりやすく。<br>

In [0]:
corona = 350
docpe = 140

corona * 2 + docpe *3

1120

#### リスト型
データをまとめて扱い際に使用するデータ型。<br>
各データの間に` , `を入れて` [ ] `で囲む。<br>
<br>
インデキシングの際はゼロから始まることに注意。

In [0]:
turanari = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

print("first number is ... ", turanari[0])
print("second number is ...", turanari[1])

first number is ...  1
second number is ... 2


#### for文
繰り返し処理を行うことができる制御構文。<br>


In [0]:
for i in turanari:
  print("number is ... ", i)
  print("i square is ... ", i**2)
  print("="*50)

number is ...  1
i square is ...  1
number is ...  2
i square is ...  4
number is ...  3
i square is ...  9
number is ...  4
i square is ...  16
number is ...  5
i square is ...  25
number is ...  6
i square is ...  36
number is ...  7
i square is ...  49
number is ...  8
i square is ...  64
number is ...  9
i square is ...  81
number is ...  10
i square is ...  100
number is ...  11
i square is ...  121
number is ...  12
i square is ...  144
number is ...  13
i square is ...  169
number is ...  14
i square is ...  196
number is ...  15
i square is ...  225
number is ...  16
i square is ...  256
number is ...  17
i square is ...  289
number is ...  18
i square is ...  324
number is ...  19
i square is ...  361


In [0]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a,b)

32

ここから実践編に入ります。<br>
いきなり専門的な知識が連発して混乱するでしょう。<br>
しかし大丈夫です。<br>
今回のハンズオンの目標はこの処理をマスターすることではなく、<br>
Pythonでこの様な処理をする事が出来ると知ることを目標としています。<br>
<br>
このハンズオンを通して得た知識を活用し、<br>
今後の学習のモチベーションや目標の発見や、<br>
Python学習の参考にして頂けるとうれしいです。<br>

# 映画レビューの感情分析をしよう
はじめに自然言語処理処理の代表的なタスクである感情分析を行ないます。<br>
感情分析とは、ある文章が肯定的な文章か否定的な文章か分類するタスクです。<br>
<br>
今回はIMDbという映画レビューサイトのレビューを用意し、<br>
あるレビューが肯定的なレビューなのか、否定的なレビューなのか、<br>
判別するロジスティック回帰モデルを実装してみましょう。<br><br>
参考: [Python機械学習プログラミング　達人データサイエンティストによる理論と実装](https://www.amazon.co.jp/Python%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0-%E9%81%94%E4%BA%BA%E3%83%87%E3%83%BC%E3%82%BF%E3%82%B5%E3%82%A4%E3%82%A8%E3%83%B3%E3%83%86%E3%82%A3%E3%82%B9%E3%83%88%E3%81%AB%E3%82%88%E3%82%8B%E7%90%86%E8%AB%96%E3%81%A8%E5%AE%9F%E8%B7%B5-impress-top-gear/dp/4844380605) 第8章<br>
***
## 自然言語処理、独特の処理をしてみよう
当然ながら自然言語は数字ではありません。
なので数字を扱う機械学習モデルに、なんの工夫なしに突っ込むことはできません。<br>
そこで、自然言語を機械学習モデルで扱えるように加工のする必要があります。<br>
今回は**BoW (Bag of Words)**という方法で加工して、<br>
機械学習モデルに突っ込んでみましょう。<br>
<br>
BoW(Bag of Words)とは……

1. 文章をトークンを作成
1. 語彙を作成する
1. 各文章で各単語の出現回数をカウントする。

はじめは簡単な文章から加工してみましょう。

In [0]:
text = np.array(["I will teach you justice with my stand",
                 "You say good bye , I say hello",
                 "Bring it on , if you want to die"])

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
bag = count.fit_transform(text)

print(count.vocabulary_)
print("-"*50)
print(bag.toarray())

{'will': 15, 'teach': 12, 'you': 17, 'justice': 7, 'with': 16, 'my': 8, 'stand': 11, 'say': 10, 'good': 3, 'bye': 1, 'hello': 4, 'bring': 0, 'it': 6, 'on': 9, 'if': 5, 'want': 14, 'to': 13, 'die': 2}
--------------------------------------------------
[[0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 1 1 1]
 [0 1 0 1 1 0 0 0 0 0 2 0 0 0 0 0 0 1]
 [1 0 1 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1]]


ここにきて3分間クッキング方式を取ります。<br>
今回はKeras.datasetsよりIMDbデータセットを拝借。<br>
手軽に実行できるのでこちらを採用。<br>
はっはっは、安定してますな。<Br>

In [0]:
from keras.datasets import imdb

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

Using TensorFlow backend.


In [0]:
print(x_test[0])

[0. 1. 1. ... 0. 0. 0.]


In [0]:
print("x_train shape : ", x_train.shape)
print("y_train shape : ", y_train.shape)
print("-"*60)
print("x_test shape : ", x_test.shape)
print("y_test shape : ", y_test.shape)

x_train shape :  (25000, 10000)
y_train shape :  (25000,)
------------------------------------------------------------
x_test shape :  (25000, 10000)
y_test shape :  (25000,)


In [0]:
y_test

array([0, 1, 1, ..., 0, 0, 0])

In [0]:
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results

x_train = vectorize_sequences(x_train)
x_test = vectorize_sequences(x_test)

x_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [0]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
print(clf.predict(x_test))

[0 1 0 ... 0 0 1]


In [0]:
print(clf.score(x_test, y_test))

0.86204


# Deep Learning で文章を生成しよう！
Deep Learning  とは先程説明したパーセプトロンを、<br>
何層も積み重ね複雑なモデルを作成したものを指します。<br>
今回はそのDeep Learningを使用して、<br>
ニーチェの文章を学習し、文章を生成してみましょう<br>
<br>
この作業を通してPythonでのDeep Learningを楽しんでいただき、<br>
今後のPython学習の参考にして頂けると幸いです。<br>
<br>
参考 : [PythonとKerasによるDeep Learning](https://www.amazon.co.jp/Python%E3%81%A8Keras%E3%81%AB%E3%82%88%E3%82%8B%E3%83%87%E3%82%A3%E3%83%BC%E3%83%97%E3%83%A9%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0-Francois-Chollet/dp/4839964262/ref=asc_df_4839964262/?tag=jpgo-22&linkCode=df0&hvadid=295719984664&hvpos=1o1&hvnetw=g&hvrand=13998509905452815517&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1009274&hvtargid=pla-527433566355&psc=1&th=1&psc=1) 8章より
***
## Deep Learning フレームワーク「Keras」
PythonにはDeep Learninを簡単に実装できるフレームワークが多数存在します。<br>
今回はその中からKerasというフレームワークを使用して実装を行います。<br>
### kerasの特徴
* 分かりやすく使いやすい記法
* 多種多彩なレイヤや機能されている
* 最近TensorFlow2.0が実装され、Kerasの重要度が上昇

### Keras の基本的な使い方
1.  Deep Learning のmodelを作成する
1. model.compileで損失関数やオプティマイザなどを選択
1. fit を使用して学習する

だいたいこれがわかってれば、なんとかなるよ。気合い。

## Step1 Kerasのインストール
はじめに pip install  を使用して Keras を準備しましょう。

In [0]:
! pip install keras

## Step2 学習データの準備
機械学習ではデータが無くては何も出来ません。<br>
今回は学習データとして使用するニーチェの文章を、<br>
下記のセルで準備しています。

In [0]:
import keras
import numpy as np

path = keras.utils.get_file(
    'nietzsche.txt',
    origin='https://s3.amazonaws.com/text-datasets/nietzsche.txt')
text = open(path).read().lower()
print('Corpus length:', len(text))

Using TensorFlow backend.


606208/600901 [==============================] - 0s 0us/step
Corpus length: 600893


## Step3  データの前処理
ここではDeep Learningで使用出来るように加工しています。<br>
機械学習ではこの様な行程を前処理と呼びます。<br>
この前処理といわれる行程は、<br>
機械学習の作業の大半を占めている非常に重要な作業です。<br>
今回の行程を具体的に覚えておく必要はありませんが、<br>
**前処理はクソ面倒かつ、重要な作業である**ことは覚えておきましょう。<br>
<br>
今回行われている具体的な処理としては……
1.
1.
1.


In [0]:
# Length of extracted character sequences
maxlen = 60

# We sample a new sequence every `step` characters
step = 3

# This holds our extracted sequences
sentences = []

# This holds the targets (the follow-up characters)
next_chars = []

for i in range(0, len(text) - maxlen, step):
    sentences.append(text[i: i + maxlen])
    next_chars.append(text[i + maxlen])
print('Number of sequences:', len(sentences))

# List of unique characters in the corpus
chars = sorted(list(set(text)))
print('Unique characters:', len(chars))
# Dictionary mapping unique characters to their index in `chars`
char_indices = dict((char, chars.index(char)) for char in chars)

# Next, one-hot encode the characters into binary arrays.
print('Vectorization...')
x = np.zeros((len(sentences), maxlen, len(chars)), dtype=np.bool)
y = np.zeros((len(sentences), len(chars)), dtype=np.bool)
for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        x[i, t, char_indices[char]] = 1
    y[i, char_indices[next_chars[i]]] = 1

Number of sequences: 200278
Unique characters: 57
Vectorization...


## Step4 モデル作成
おまたせしました。<br>
今回の処理で使用するDeep Learning のモデルを作成します。<br>
Kerasでの書き方はとっても簡単。<br>
<br>
自分が作成するモデルの各層をリスト型として纏めるだけ。<br>
これでチャチャっとDeepLearning出来るのだから驚き。<br>
とっても簡単だから、みんなもDeep Learningしようぜ！<br>

In [0]:
from keras import layers

model = keras.models.Sequential()
model.add(layers.LSTM(128, input_shape=(maxlen, len(chars))))
model.add(layers.Dense(len(chars), activation='softmax'))

## Step5 Optimizer と lossを決定する
今日は……直感で大丈夫です。<br>
ザックリ説明するとDeepLearningを学習するにあたって<br>
どの様な方針で学習するのか　(Loss)<br>
どの様な方法で学習するのか　(Optimizer)<br>
だと思ってください。<br>
<br>
ここで重要なのは...<br>
下記のセルの様に簡単に設定が可能である点です。<Br>
これなら初学者の私もニッコリですね。<br>

In [0]:
optimizer = keras.optimizers.RMSprop(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=optimizer)

## Step6 学習開始！
ここから学習の開始です！


In [0]:
def sample(preds, temperature=1.0):
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)

In [0]:
import random
import sys

for epoch in range(1, 60):
    print('epoch', epoch)
    # Fit the model for 1 epoch on the available training data
    model.fit(x, y,
              batch_size=128,
              epochs=1)

    # Select a text seed at random
    start_index = random.randint(0, len(text) - maxlen - 1)
    generated_text = text[start_index: start_index + maxlen]
    print('--- Generating with seed: "' + generated_text + '"')

    for temperature in [0.2, 0.5, 1.0, 1.2]:
        print('------ temperature:', temperature)
        sys.stdout.write(generated_text)

        # We generate 400 characters
        for i in range(400):
            sampled = np.zeros((1, maxlen, len(chars)))
            for t, char in enumerate(generated_text):
                sampled[0, t, char_indices[char]] = 1.

            preds = model.predict(sampled, verbose=0)[0]
            next_index = sample(preds, temperature)
            next_char = chars[next_index]

            generated_text += next_char
            generated_text = generated_text[1:]

            sys.stdout.write(next_char)
            sys.stdout.flush()
        print()

W0706 15:05:17.810219 139667803760512 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


epoch 1


W0706 15:05:18.482542 139667803760512 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/1
200278/200278 [==============================] - 260s 1ms/step - loss: 1.9822
--- Generating with seed: "torical sense, which we europeans claim as our specialty, ha"
------ temperature: 0.2
torical sense, which we europeans claim as our specialty, have in the self-conders the conder to god the conders and the self-conding the sould condinged to such and a peris of the man the greated and a such and something in the sees and sees of the self-created and strenge the self-conders the sees to the sees the sees and a far to the sees a possicely sees to the conder to the was the strenge the suct and the self-condect of the sees the seems and sould 
------ temperature: 0.5
e suct and the self-condect of the sees the seems and sould been preces to the porned to
greated to the does in who concerental we are it as the sould and the should to love, in from the denerational speen who sould in in a man in the sense of the seems higher and man in the powild in greation of the percounted t

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


uspabting obtriams one that of distingifyists ratings,", let us wearing eod-clears hus have from nelsed and actions feels his reasonings, as stope
s
epoch 11
Epoch 1/1
200278/200278 [==============================] - 256s 1ms/step - loss: 1.3846
--- Generating with seed: "y. the practical indifference to religious
matters in the mi"
------ temperature: 0.2
y. the practical indifference to religious
matters in the minds of the superiority of the presenter of the same the stringt of the spirit to the sense of the same the states the subturious and states the same the same the same the most present the fact of the same the same the most present and contradiction of the sense of the effect to the fact the actions of the same the same the contradiction of the same the same the fact the same the same the strength 
------ temperature: 0.5
f the same the same the fact the same the same the strength and
condetions of the last man be the counter in the as the experience for instance, and all the